export const RUN_COMMAND_REQUEST = "RUN_COMMAND_REQUEST";
export const RUN_COMMAND_RESULT = "RUN_COMMAND_RESULT";

export const ADD_NEW_SESSION = "ADD_NEW_SESSION";
export const REMOVE_SESSION = "REMOVE_SESSION";
